language: go
sudo: required
go_import_path: github.com/csi-driver/csi-driver-smb
dist: bionic
services:
  - docker
go:
  - "1.13.9"

jobs:
  include:
    - stage: test
      name: "build test"
      script:
        - make verify
        - make smb-windows
        - make container
    - stage: test
      name: "integration test"
      install:
        - GO111MODULE=off go get github.com/rexray/gocsi/csc
        - sudo apt update && sudo apt install cifs-utils procps -y
      script:
        - make
        - make integration-test
    - stage: test
      name: "sanity test"
      install:
        - sudo apt update && sudo apt install cifs-utils procps -y
      script:
        - make
        - make sanity-test
    - stage: test
      name: "e2e test"
      before_install:
        - sudo apt-get -qq -y install conntrack
      script:
        - source test/utils/deploy-minikube.sh
        - make
        - make e2e-test
