apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: ip-space
      protocol: layer2
      addresses:
      - 172.16.1.0/24
