apiVersion: v1
data:
  secretkey: NDhUQmFUbUo0YVpqQjFEMGFUbWhjSjJ0OTlUR0EvUXI1cklVZTRqUjBYUC8xQllJMTZZQnFpUnhKN2FHaVdHKwpjV3VTWENxYk1wS1VsdkV6d2g1SnNZZDBtekE0QXY4dS84V1BTT0t4cVovZnpiSjI4NXVJek8vQ01OU2EvbzZtClc2S0JveVRkNEFpMFREVlNqTTg3YTREQ09qWXpnZ0FRb3VWdXcxemszMnc9
kind: Secret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
