apiVersion: v1
data:
  secretkey: M1NhNlBYUndoVjhUd3BkL3Blczdkdit4bFFXbUZDSnVEQmhTTGlDZm9FeGhGZ3hjQnllQmVmcWFvZWJLUVJqSApIVjl4OVUzRnZkeUp1cjY1S0xRUTlCUk1jNmxTSHZveGdSU1phcGU5ZHhmNEhLMCtPSlRTdUw5Zkt1enBIQjM2CnhvckVJYzdUVGFnZnVCUGg1aElvcXlYeE5UM3VseTl3TmxmNnd6T1FqdzQ9
kind: Secret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
