apiVersion: v1
data:
  secretkey: OHdPdXJ1Z2d3ZU5OOGRPemJVZE9VOFNkakZGVEdOU3crajNabGNBMTUvb1BOODRDTWpqRWN6TnQ4K3JUOWw1TgpGaTArMkZEL09lVlp4dThNcnRaQjZoNjV1M01rU3hXOFBqeHR2QmVKb2hNaWZEZS8yTzBIZVN0a2dnRkpneGhkCkVVZ2lteUREcURGc21mUmlOeVhrdzRXbFpJUUVtZ1dEWXBha1JUSk5zbDg9
kind: Secret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
