apiVersion: v1
data:
  secretkey: MnFtSGpvRWgwTjd2bzVPUnByUnpVWVpOUTFtK3dZVFhlWk9oRC9kMFdIK0VwUE43dkEvemdHa1FKSlY0OW1LLwovL084WU9tMXYvZXA3RVRkQklPdHplV095VDcxZnV6Qi9idThCVldKd2UxaUNsSTlsWjdqS1dIVGg4WHFGdC9SClpGUVNMMnlObmkxeHVhQnBrbW01NjJLd0pTZVE3THI4Y0lBWks5TnZUV1k9
kind: Secret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
