apiVersion: v1
kind: Service
metadata:
  name: smb-server-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: smb-server
spec:
  ports:
  - port: 139
    targetPort: 139
    protocol: TCP
    name: port-139
  - port: 445
    targetPort: 445
    protocol: TCP
    name: port-445
  selector:
    app: smb-server
  type: LoadBalancer
  loadBalancerIP: 172.16.1.2

---
apiVersion: v1
kind: Service
metadata:
  name: smb-server-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: smb-server
spec:
  ports:
  - port: 137
    targetPort: 137
    protocol: UDP
    name: port-137
  - port: 138
    targetPort: 138
    protocol: UDP
    name: port-138
  selector:
    app: smb-server
  type: LoadBalancer
  loadBalancerIP: 172.16.1.2