apiVersion: apps/v1
kind: Deployment
metadata:
  name: smb-server
  labels:
    app: smb-server
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 
      maxUnavailable: 1
  selector:
    matchLabels:
      app: smb-server
  template:
    metadata:
      labels:
        app: smb-server
        configmap-version: "2"
    spec:
      containers:
      - name: smb-server
        image: brycemclachlan/smb-server:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: tv
          mountPath: /srv/tv
        - name: movies
          mountPath: /srv/movies
        - name: games
          mountPath: /srv/games
        - name: downloads
          mountPath: /srv/downloads
        - name: videos
          mountPath: /srv/videos
        - name: samba-config
          mountPath: /etc/samba/
      restartPolicy: Always
      volumes:
      - name: tv
        persistentVolumeClaim:
          claimName: tv
      - name: movies
        persistentVolumeClaim:
          claimName: movies
      - name: games
        persistentVolumeClaim:
          claimName: games
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads
      - name: videos
        persistentVolumeClaim:
          claimName: videos
      - name: samba-config
        configMap:
          name: samba-config