apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: smb-server
  labels:
    app: smb-server
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: smb-server
        image: brycemclachlan/smb-server:latest
        imagePullPolicy: Always
        restartPolicy: Always
        volumeMounts:
        - name: tv
          mountPath: /srv/tv
        - name: movies
          mountPath: /srv/movies
        - name: games
          mountPath: /srv/games
        - name: downloads
          mountPath: /srv/downloads
        - name: videos
          mountPath: /srv/videos
        - name: samba-config
          mountPath: /etc/samba/smb.conf
      volumes:
      - name: tv
        persistentVolumeClaim:
          claimName: tv
      - name: movies
        persistentVolumeClaim:
          claimName: movies
      - name: games
        persistentVolumeClaim:
          claimName: games
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads
      - name: videos
        persistentVolumeClaim:
          claimName: videos
      - name: samba-config
        configMap:
          name: samba-config