kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: photos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6000Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6000Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: movies
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6000Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: games
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6000Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: downloads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6000Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: videos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6000Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: anacleto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6000Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bryce
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi