apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v15
  mgr:
    modules:
    - name: pg_autoscaler
      enabled: true
  resources:
    mgr:
      limits:
        cpu: ".25"
        memory: "512Mi"
      requests:
        cpu: ".25"
        memory: "512Mi"
    mon:
      limits:
        cpu: ".5"
        memory: "1024Mi"
      requests:
        cpu: ".5"
        memory: "1024Mi"
    osd:
      limits:
        cpu: "1"
        memory: "2048Mi"
      requests:
        cpu: "1"
        memory: "2048Mi"
    prepareosd:
      limits:
        cpu: ".25"
        memory: "256Mi"
      requests:
        cpu: ".25"
        memory: "256Mi"
    crashcollector:
      limits:
        cpu: ".25"
        memory: "256Mi"
      requests:
        cpu: ".25"
        memory: "256Mi"