apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rook-cephfs
provisioner: rook-ceph.cephfs.csi.ceph.com
parameters:
  fsName: myfs-ec

  # Ceph pool into which the volume shall be created
  # Required for provisionVolume: "true"
  pool: ec-data-pool
