apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph
resources:
##Cluster setting
- rook/cluster/examples/kubernetes/ceph/common.yaml
- rook/cluster/examples/kubernetes/ceph/operator.yaml
- rook/cluster/examples/kubernetes/ceph/cluster.yaml
#Block storage
- rook/cluster/examples/kubernetes/ceph/csi/rbd/storageclass-ec.yaml
patchesStrategicMerge:
#Block storage
- replicated-metadata-pool.yaml
- default-storage-class.yaml