apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph
resources:
##Cluster setting
- rook/cluster/examples/kubernetes/ceph/common.yaml
- rook/cluster/examples/kubernetes/ceph/operator.yaml
- cluster-test.yaml
#Block storage
- rook/cluster/examples/kubernetes/ceph/csi/rbd/storageclass-test.yaml
patchesStrategicMerge:
#Block storage
- default-storage-class.yaml
- cephVersion.yaml