apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
#- namespace.yaml
- pvc.yaml
#- job-tv.yaml
#- job-movies.yaml
#- job-other.yaml
#- job-games.yaml
- job-downloads.yaml