apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2020-05-19T19:29:06Z"
  generation: 2128
  managedFields:
  - apiVersion: argoproj.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:destination:
          .: {}
          f:namespace: {}
          f:server: {}
        f:project: {}
        f:source:
          .: {}
          f:path: {}
          f:repoURL: {}
          f:targetRevision: {}
        f:syncPolicy:
          .: {}
          f:automated:
            .: {}
            f:prune: {}
          f:syncOptions: {}
      f:status:
        .: {}
        f:health: {}
        f:summary: {}
        f:sync:
          .: {}
          f:comparedTo:
            .: {}
            f:destination: {}
            f:source: {}
    manager: argocd-server
    operation: Update
    time: "2020-05-20T03:11:19Z"
  - apiVersion: argoproj.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:operation:
        .: {}
        f:initiatedBy:
          .: {}
          f:automated: {}
        f:sync:
          .: {}
          f:prune: {}
          f:revision: {}
          f:syncOptions: {}
      f:status:
        f:conditions: {}
        f:health:
          f:status: {}
        f:observedAt: {}
        f:operationState:
          .: {}
          f:message: {}
          f:operation:
            .: {}
            f:initiatedBy:
              .: {}
              f:automated: {}
            f:sync:
              .: {}
              f:prune: {}
              f:revision: {}
              f:syncOptions: {}
          f:phase: {}
          f:startedAt: {}
          f:syncResult:
            .: {}
            f:revision: {}
            f:source:
              .: {}
              f:path: {}
              f:repoURL: {}
              f:targetRevision: {}
        f:reconciledAt: {}
        f:resources: {}
        f:sourceType: {}
        f:summary:
          f:images: {}
        f:sync:
          f:comparedTo:
            f:destination:
              f:namespace: {}
              f:server: {}
            f:source:
              f:path: {}
              f:repoURL: {}
              f:targetRevision: {}
          f:revision: {}
          f:status: {}
    manager: argocd-application-controller
    operation: Update
    time: "2020-05-20T21:21:51Z"
  name: argocd
  namespace: argocd
  resourceVersion: "809979"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/applications/argocd
  uid: 5a8e9c1e-e2e0-428c-8411-73866fd730ec
operation:
  initiatedBy:
    automated: true
  sync:
    prune: true
    revision: 34217877d9d8d43990f8e4b9b4d7af5378ce683b
    syncOptions:
    - Validate=false
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: git@github.com:brycemcl/kube-cluster.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - Validate=false
status:
  conditions:
  - lastTransitionTime: "2020-05-19T19:29:14Z"
    message: Application has 1 orphaned resources
    type: OrphanedResourceWarning
  health:
    status: Healthy
  observedAt: "2020-05-20T21:21:50Z"
  operationState:
    message: one or more tasks are running
    operation:
      initiatedBy:
        automated: true
      sync:
        prune: true
        revision: 34217877d9d8d43990f8e4b9b4d7af5378ce683b
        syncOptions:
        - Validate=false
    phase: Running
    startedAt: "2020-05-20T03:13:22Z"
    syncResult:
      revision: 34217877d9d8d43990f8e4b9b4d7af5378ce683b
      source:
        path: .
        repoURL: git@github.com:brycemcl/kube-cluster.git
        targetRevision: HEAD
  reconciledAt: "2020-05-20T21:19:49Z"
  resources:
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: rook-ceph-cmd-reporter
    namespace: rook-ceph
    status: Synced
    version: v1beta1
  - kind: Namespace
    name: metallb-system
    status: Synced
    version: v1
  - kind: ServiceAccount
    name: rook-ceph-system
    namespace: rook-ceph
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: rook-ceph-global-rules
    status: Synced
    version: v1beta1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: rook-ceph-object-bucket
    status: Synced
    version: v1beta1
  - kind: ServiceAccount
    name: speaker
    namespace: metallb-system
    status: Synced
    version: v1
  - kind: ServiceAccount
    name: rook-ceph-mgr
    namespace: rook-ceph
    status: Synced
    version: v1
  - kind: ServiceAccount
    name: rook-csi-rbd-provisioner-sa
    namespace: rook-ceph
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: rook-ceph-cluster-mgmt
    status: OutOfSync
    version: v1beta1
  - kind: Secret
    name: memberlist
    namespace: metallb-system
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cilium
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: psp:rook
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: rook-ceph-mgr-cluster
    status: OutOfSync
    version: v1beta1
  - group: rbac.authorization.k8s.io
    kind: Role
    name: config-watcher
    namespace: metallb-system
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: Role
    name: rbd-external-provisioner-cfg
    namespace: rook-ceph
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: ingress-nginx
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: cephfs-csi-provisioner-role
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: cilium-operator
    status: Synced
    version: v1
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: cephclusters.ceph.rook.io
    status: Synced
    version: v1beta1
  - group: rbac.authorization.k8s.io
    kind: Role
    name: pod-lister
    namespace: metallb-system
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: metallb-system:controller
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: rook-ceph-global
    status: OutOfSync
    version: v1beta1
  - group: rbac.authorization.k8s.io
    kind: Role
    name: cephfs-external-provisioner-cfg
    namespace: rook-ceph
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: rook-ceph-osd-psp
    namespace: rook-ceph
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: rbd-csi-provisioner-role-cfg
    namespace: rook-ceph
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: rook-ceph-osd
    namespace: rook-ceph
    status: Synced
    version: v1beta1
  - group: rbac.authorization.k8s.io
    kind: Role
    name: rook-ceph-cmd-reporter
    namespace: rook-ceph
    status: Synced
    version: v1beta1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: metallb-system:speaker
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: rook-csi-cephfs-plugin-sa-psp
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: rook-csi-rbd-provisioner-sa-psp
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: rook-ceph-object-bucket
    status: Synced
    version: v1beta1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: rook-ceph-mgr-cluster
    status: Synced
    version: v1beta1
  - health:
      status: Healthy
    kind: Service
    name: ingress-nginx-controller
    namespace: ingress-nginx
    status: Synced
    version: v1
  - kind: ConfigMap
    name: cilium-config
    namespace: kube-system
    status: Synced
    version: v1
  - kind: ConfigMap
    name: rook-ceph-operator-config
    namespace: rook-ceph
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: cilium-operator
    namespace: kube-system
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cephfs-csi-nodeplugin-rules
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: rook-csi-cephfs-provisioner-sa-psp
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cephfs-csi-nodeplugin
    status: OutOfSync
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: rbd-csi-nodeplugin-rules
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: rook-ceph-global
    status: Synced
    version: v1beta1
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: objectbucketclaims.objectbucket.io
    status: Synced
    version: v1beta1
  - group: policy
    kind: PodSecurityPolicy
    name: controller
    status: Synced
    version: v1beta1
  - group: policy
    kind: PodSecurityPolicy
    name: 00-rook-privileged
    status: Synced
    version: v1beta1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: ingress-nginx
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: ingress-nginx-controller
    namespace: ingress-nginx
    status: Synced
    version: v1
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: cephobjectstores.ceph.rook.io
    status: Synced
    version: v1beta1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: rbd-csi-nodeplugin
    status: OutOfSync
    version: v1
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: rook-ceph-cluster-mgmt
    namespace: rook-ceph
    status: Synced
    version: v1beta1
  - health:
      status: Healthy
    kind: Service
    name: ingress-nginx-controller-admission
    namespace: ingress-nginx
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: DaemonSet
    name: cilium
    namespace: kube-system
    status: Synced
    version: v1
  - kind: Namespace
    name: rook-ceph
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: Role
    name: rook-ceph-mgr
    namespace: rook-ceph
    status: Synced
    version: v1beta1
  - group: rbac.authorization.k8s.io
    kind: Role
    name: rook-ceph-osd
    namespace: rook-ceph
    status: Synced
    version: v1beta1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: rook-ceph-mgr-cluster-rules
    status: Synced
    version: v1beta1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: cephfs-csi-nodeplugin
    status: Synced
    version: v1
  - kind: ServiceAccount
    name: cilium-operator
    namespace: kube-system
    status: Synced
    version: v1
  - kind: ServiceAccount
    name: rook-csi-rbd-plugin-sa
    namespace: rook-ceph
    status: Synced
    version: v1
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: cephblockpools.ceph.rook.io
    status: Synced
    version: v1beta1
  - kind: ServiceAccount
    name: cilium
    namespace: kube-system
    status: Synced
    version: v1
  - kind: ServiceAccount
    name: rook-ceph-osd
    namespace: rook-ceph
    status: Synced
    version: v1
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: cephnfses.ceph.rook.io
    status: Synced
    version: v1beta1
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: objectbuckets.objectbucket.io
    status: Synced
    version: v1beta1
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: cephobjectstoreusers.ceph.rook.io
    status: Synced
    version: v1beta1
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: cephfs-csi-provisioner-role-cfg
    namespace: rook-ceph
    status: Synced
    version: v1
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: volumes.rook.io
    status: Synced
    version: v1beta1
  - group: rbac.authorization.k8s.io
    kind: Role
    name: rook-ceph-system
    namespace: rook-ceph
    status: Synced
    version: v1beta1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cilium-operator
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: pod-lister
    namespace: metallb-system
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: DaemonSet
    name: speaker
    namespace: metallb-system
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: rook-ceph-operator
    namespace: rook-ceph
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: Role
    name: ingress-nginx
    namespace: ingress-nginx
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: rook-ceph-default-psp
    namespace: rook-ceph
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: rook-ceph-mgr-system
    namespace: rook-ceph
    status: Synced
    version: v1beta1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: metallb-system:controller
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: controller
    namespace: metallb-system
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: metallb-system:speaker
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: rook-ceph-system-psp
    status: Synced
    version: v1
  - kind: Namespace
    name: ingress-nginx
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: rook-ceph-mgr-psp
    namespace: rook-ceph
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: rook-ceph-mgr
    namespace: rook-ceph
    status: Synced
    version: v1beta1
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: config-watcher
    namespace: metallb-system
    status: Synced
    version: v1
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: cephclients.ceph.rook.io
    status: Synced
    version: v1beta1
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: cephfilesystems.ceph.rook.io
    status: Synced
    version: v1beta1
  - kind: ServiceAccount
    name: ingress-nginx
    namespace: ingress-nginx
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: rook-ceph-mgr-system-rules
    status: Synced
    version: v1beta1
  - kind: ServiceAccount
    name: rook-csi-cephfs-provisioner-sa
    namespace: rook-ceph
    status: Synced
    version: v1
  - group: policy
    kind: PodSecurityPolicy
    name: speaker
    status: Synced
    version: v1beta1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: rook-ceph-cluster-mgmt-rules
    status: Synced
    version: v1beta1
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: ingress-nginx
    namespace: ingress-nginx
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: rook-ceph-system
    namespace: rook-ceph
    status: Synced
    version: v1beta1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: rbd-csi-nodeplugin
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: rook-ceph-osd
    status: Synced
    version: v1beta1
  - kind: ServiceAccount
    name: rook-csi-cephfs-plugin-sa
    namespace: rook-ceph
    status: Synced
    version: v1
  - kind: ServiceAccount
    name: rook-ceph-cmd-reporter
    namespace: rook-ceph
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: cilium
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cephfs-external-provisioner-runner
    status: OutOfSync
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: rook-ceph-osd
    status: Synced
    version: v1beta1
  - group: ceph.rook.io
    kind: CephCluster
    name: rook-ceph
    namespace: rook-ceph
    status: OutOfSync
    version: v1
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: ingress-nginx-admission
    status: Synced
    version: v1beta1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: rbd-external-provisioner-runner
    status: OutOfSync
    version: v1
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
    name: rook-ceph-cmd-reporter-psp
    namespace: rook-ceph
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: rbd-csi-provisioner-role
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: rook-csi-rbd-plugin-sa-psp
    status: Synced
    version: v1
  - kind: ConfigMap
    name: config
    namespace: metallb-system
    status: Synced
    version: v1
  - kind: ServiceAccount
    name: controller
    namespace: metallb-system
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cephfs-external-provisioner-runner-rules
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: rook-ceph-mgr-system
    status: OutOfSync
    version: v1beta1
  - kind: ConfigMap
    name: ingress-nginx-controller
    namespace: ingress-nginx
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: rbd-external-provisioner-runner-rules
    status: Synced
    version: v1
  - group: rbac.authorization.k8s.io
    health:
      message: Pending deletion
      status: Progressing
    hook: true
    kind: RoleBinding
    name: ingress-nginx-admission
    namespace: ingress-nginx
    requiresPruning: true
    version: v1
  - group: rbac.authorization.k8s.io
    health:
      message: Pending deletion
      status: Progressing
    hook: true
    kind: Role
    name: ingress-nginx-admission
    namespace: ingress-nginx
    requiresPruning: true
    version: v1
  sourceType: Kustomize
  summary:
    images:
    - quay.io/k8scsi/csi-node-driver-registrar:v1.2.0
    - quay.io/cephcsi/cephcsi:v2.1.1
    - quay.io/k8scsi/csi-provisioner:v1.4.0
    - rook/ceph:v1.3.3
    - metallb/controller:v0.9.3
    - quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.32.0
    - docker.io/cilium/cilium:v1.7.4
    - metallb/speaker:v0.9.3
    - quay.io/k8scsi/csi-resizer:v0.4.0
    - quay.io/k8scsi/csi-attacher:v2.1.0
    - quay.io/k8scsi/csi-snapshotter:v1.2.2
    - ceph/ceph:v14.2.9
    - docker.io/cilium/operator:v1.7.4
  sync:
    comparedTo:
      destination:
        namespace: default
        server: https://kubernetes.default.svc
      source:
        path: .
        repoURL: git@github.com:brycemcl/kube-cluster.git
        targetRevision: HEAD
    revision: 99110440dd454e64ab279cba5f7afe600786a157
    status: OutOfSync
