apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"AppProject","metadata":{"annotations":{},"name":"default","namespace":"argocd"},"spec":{"clusterResourceWhitelist":[{"group":"*","kind":"*"}],"description":"default","destinations":[{"namespace":"*","server":"*"}],"orphanedResources":{"warn":true},"sourceRepos":["*"]}}
  creationTimestamp: "2020-05-19T06:18:25Z"
  generation: 2
  managedFields:
  - apiVersion: argoproj.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:clusterResourceWhitelist: {}
        f:destinations: {}
        f:sourceRepos: {}
    manager: argocd-server
    operation: Update
    time: "2020-05-19T06:18:25Z"
  - apiVersion: argoproj.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        f:description: {}
        f:orphanedResources:
          .: {}
          f:warn: {}
    manager: kubectl
    operation: Update
    time: "2020-05-19T19:03:09Z"
  name: default
  namespace: argocd
  resourceVersion: "270954"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/appprojects/default
  uid: 664ed8af-6d06-4cad-8cc4-058816f4f12f
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: default
  destinations:
  - namespace: '*'
    server: '*'
  orphanedResources:
    warn: true
  sourceRepos:
  - '*'
