apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":null,"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-tls-certs-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-tls-certs-cm","namespace":"argocd"}}
  creationTimestamp: "2020-05-20T22:28:13Z"
  labels:
    app.kubernetes.io/name: argocd-tls-certs-cm
    app.kubernetes.io/part-of: argocd
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/part-of: {}
    manager: kubectl
    operation: Update
    time: "2020-05-20T22:28:13Z"
  name: argocd-tls-certs-cm
  namespace: argocd
  resourceVersion: "834535"
  selfLink: /api/v1/namespaces/argocd/configmaps/argocd-tls-certs-cm
  uid: fea8f874-f2f3-46fc-86d5-8db25b5c6b9f
