apiVersion: v1
kind: Service
metadata:
  name: smb-server-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: smb-server
spec:
  ports:
##syncthing
  - name: port-8384
    port: 443
    protocol: TCP
    targetPort: 8384
  - name: port-22000
    port: 22000
    protocol: TCP
    targetPort: 22000
##samba
  - name: port-139
    port: 139
    protocol: TCP
    targetPort: 139
  - name: port-445
    port: 445
    protocol: TCP
    targetPort: 445
  selector:
    app: smb-server
  type: LoadBalancer
  loadBalancerIP: 172.16.10.3
---
apiVersion: v1
kind: Service
metadata:
  name: smb-server-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: smb-server
spec:
  ports:
##syncthing
  - name: port-21027
    port: 21027
    protocol: UDP
    targetPort: 21027
##samba
  - name: port-137
    port: 137
    protocol: UDP
    targetPort: 137
  - name: port-138
    port: 138
    protocol: UDP
    targetPort: 138
  selector:
    app: smb-server
  type: LoadBalancer
  loadBalancerIP: 172.16.10.3