image:
  smb:
    repository: mcr.microsoft.com/k8s/csi/smb-csi
    tag: v0.1.0
    pullPolicy: IfNotPresent
  livenessProbe:
    repository: mcr.microsoft.com/oss/kubernetes-csi/livenessprobe
    tag: v1.1.0
    pullPolicy: IfNotPresent
  nodeDriverRegistrar:
    repository: mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar
    tag: v1.2.0
    pullPolicy: IfNotPresent

linux:
  enabled: true

windows:
  enabled: false
  image:
    livenessProbe:
      repository: mcr.microsoft.com/oss/kubernetes-csi/livenessprobe
      tag: v2.0.1-alpha.1-windows-1809-amd64
      pullPolicy: IfNotPresent
    nodeDriverRegistrar:
      repository: mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar
      tag: v1.2.1-alpha.1-windows-1809-amd64
      pullPolicy: IfNotPresent
