apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  labels:
    app: radarr
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 
      maxUnavailable: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
        configmap-version: "15"
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
              - topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app: smb-server
                namespaces: ["media"]
      containers:
      - env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: Canada/Pacific
        - name: UMASK_SET
          value: "000"
        name: radarr
        image: linuxserver/radarr
        imagePullPolicy: Always
        resources: 
          limits:
            cpu: "2"
            memory: "1000Mi"
          requests:
            cpu: ".1"
            memory: "100Mi"
        volumeMounts:
        - name: bryce
          mountPath: /srv/bryce
        - name: anacleto
          mountPath: /srv/anacleto
        - name: photos
          mountPath: /srv/photos
        - name: tv
          mountPath: /srv/tv
        - name: movies
          mountPath: /srv/movies
        - name: games
          mountPath: /srv/games
        - name: downloads
          mountPath: /srv/downloads
          readOnly: true
        - name: videos
          mountPath: /srv/videos
        - name: radarr-config
          mountPath: /config
      volumes:
      - name: photos
        persistentVolumeClaim:
          claimName: smb-photos
      - name: tv
        persistentVolumeClaim:
          claimName: smb-tv
      - name: movies
        persistentVolumeClaim:
          claimName: smb-movies
      - name: games
        persistentVolumeClaim:
          claimName: smb-games
      - name: downloads
        persistentVolumeClaim:
          claimName: smb-downloads
      - name: videos
        persistentVolumeClaim:
          claimName: smb-videos
      - name: anacleto
        persistentVolumeClaim:
          claimName: smb-anacleto
      - name: bryce
        persistentVolumeClaim:
          claimName: smb-bryce
      - name: radarr-config
        persistentVolumeClaim:
          claimName: radarr-config