apiVersion: v1
kind: PersistentVolume
metadata:
  name: jcr-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 6000Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pvc/jcr-data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing-config
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pvc/syncthing-config"