apiVersion: v1
data:
  smb.conf: |
    # Global parameters
    [global]
            dns proxy = No
            map to guest = Bad User
            name resolve order = bcast host
            netbios name = SERVER
            security = USER
            server string = Server %v
            idmap config * : backend = tdb


    [Server]
            create mask = 0777
            guest ok = Yes
            path = /srv/server
            read only = No
            hide unreadable = yes

kind: ConfigMap
metadata:
  name: samba-config