apiVersion: apps/v1
kind: Deployment
metadata:
  name: smb-server
  labels:
    app: smb-server
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 
      maxUnavailable: 1
  selector:
    matchLabels:
      app: smb-server
  template:
    metadata:
      labels:
        app: smb-server
        configmap-version: "11"
    spec:
      containers:
      - env:
        - name: PGID
          value: "0"
        - name: PUID
          value: "0"
        - name: TZ
          value: Canada/Pacific
        - name: UMASK_SET
          value: "022"
        name: syncthing
        image: linuxserver/syncthing
        imagePullPolicy: Always
        ports:
        - containerPort: 8384
        - containerPort: 22000
        - containerPort: 21027
          protocol: UDP
        resources: 
          limits:
            cpu: "2"
            memory: "4000Mi"
          requests:
            cpu: "1"
            memory: "500Mi"
        volumeMounts:
        - mountPath: /config
          name: syncthing-config
        - mountPath: /data
          name: jcr-data
      - name: smb-server
        image: brycemclachlan/smb-server:latest
        imagePullPolicy: Always
        resources: 
          limits:
            cpu: "2"
            memory: "1000Mi"
          requests:
            cpu: ".1"
            memory: "100Mi"
        volumeMounts:
        - name: jcr-data
          mountPath: /srv/server
        - name: samba-config
          mountPath: /etc/samba/
      restartPolicy: Always
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
      - name: jcr-data
        persistentVolumeClaim:
          claimName: jcr-data
      - name: samba-config
        configMap:
          name: samba-config
      - name: syncthing-config
        persistentVolumeClaim:
          claimName: syncthing-config