apiVersion: v1
data:
  smb.conf: |
    # Global parameters
    [global]
            dns proxy = No
            map to guest = Bad User
            name resolve order = bcast host
            netbios name = server-backup
            security = USER
            server string = Server
            idmap config * : backend = tdb

    [server]
            create mask = 0777
            guest ok = Yes
            path = /srv/server/Server
            read only = No
            hide unreadable = yes
            writable = yes
            create mode = 0777
            force directory mode = 0777

kind: ConfigMap
metadata:
  name: samba-config