apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  destination:
    namespace: '*'
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'git@github.com:brycemcl/kube-cluster.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
